#! /usr/bin/env bash

set -e # exit on error
set -x

TOP=${TOP:-$(git rev-parse --show-toplevel)}
EXT=$TOP/ext

subtree()
{
    local project="$1"
    local cmd="add"

    shift

    if [ -d ext/"$project" ] ; then
        cmd="pull"
    fi

    git subtree $cmd \
        --prefix=ext/$project \
        --squash \
        "$@"
}

echo updating libphenom to master ...
(
    pushd $TOP
    subtree libphenom \
        --message "Update libphenom" \
        https://github.com/facebook/libphenom.git \
        master
)

