#! /usr/bin/env bash

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# make-forwarding-header FILE [FILE...]
# Generate a standard forwarding header for <sys/...> includes used by
# Solaris code.

PROGNAME="$(basename $0)"

ASPL='
/** @file
 *
 *  A brief file description
 *
 *  @section license License
 *
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
'

mkguard() {
  name=`basename "$1"`
  year=`date +%Y`
  uuid=`uuidgen`

  echo ${name}_${uuid} | tr a-z A-Z | sed 's/[-. ]/_/g'
}

mkheader()
{
  echo making $1

  path="$1"
  guard=$(mkguard "$path")

cat > "$path" <<EOF
$ASPL

#ifndef $guard
#define $guard

#include <spl/$(basename "$1")>

#endif /* $guard */
EOF
}

mknull()
{
  echo making $1

  path="$1"
  guard=$(mkguard "$path")

cat > "$path" <<EOF
$ASPL

#ifndef $guard
#define $guard

#endif /* $guard */
EOF
}

while : ; do
  if [ -z "$1" ]; then
    exit
  fi

  if [ -e "$1" ] ; then
    echo $1 exists
    continue
  fi

  (
    cd src/include/sys

    if [ ! -e $(dirname "$path") ]; then
      mkdir -p $(dirname "$path")
    fi

    case $PROGNAME in
    make-null-header)
      mknull $(basename "$1") ;;
    make-forwarding-header)
      mkheader $(basename "$1") ;;
    *) ;;
    esac

  )

  shift
done

# vim: set ts=2 sw=2 sts=2 et:
