#! /usr/bin/env bash

TOP=${TOP:-$(git rev-parse --show-toplevel)}

cd $TOP

if [ ! -d .openzfs ]; then
    git clone https://github.com/openzfs/openzfs.git .openzfs
fi

(
    cd .openzfs

    git checkout master
    git pull

    git branch -D zfs || true
    git subtree split --prefix=usr/src/uts/common/fs/zfs --branch=zfs

    git branch -D common || true
    git subtree split --prefix=usr/src/common/zfs --branch=common
)

if [ -d src/fs/zfs ]; then
    git subtree pull  --prefix=src/fs/zfs $(pwd)/.openzfs zfs
else
    git subtree add  --prefix=src/fs/zfs $(pwd)/.openzfs zfs
fi

if [ -d src/fs/common ]; then
    git subtree pull  --prefix=src/fs/common $(pwd)/.openzfs common
else
    git subtree add  --prefix=src/fs/common $(pwd)/.openzfs common
fi

#rm -rf .openzfs
